name: Go

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  client-build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"
          cache: true

      - name: Run Go generators
        run: go generate ./.../gen

      - name: Ensure generated code is clean
        run: git diff --exit-code

      - name: Run Go vet
        run: go vet ./...

      - name: Build Go
        run: go build ./...

      - name: Install gotestsum
        run: go install gotest.tools/gotestsum@v1.12.0

      - name: Run Go tests
        run: gotestsum

      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@v1.1.0

      - name: Run govulncheck
        run: govulncheck ./...

  client-scan:
    if: github.event_name != 'schedule'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: securego/gosec@v2.19.0
        with:
          args: ./...

  client-lint:
    if: github.event_name != 'schedule'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Lint Go
        uses: keep-network/golint-action@v1.0.2
